apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:N4zdGQhTSGQRhtlubcC9dXpLPOHcVNw/VD7KqvF/24IZvBxiErSR+aiYD/CN3HPX55WM65u6hWW9ij1xW2LGEtCjgUT90PgSsU6Bx5Co65Kg70xwlnQ7FFBfd/uOe7t8Rv/+lM/TRO9P5JcBMgWj7tYQGG/3TRdEWg==,iv:XTOWW8JUDRm631gqNL2VIlllJ3Od/qEZbJJFmgwdqY0=,tag:3S+8Ncm4pJ7CltD4yKnfmg==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dXFab095UWg2VTZHTU44
            aWJvQ1hMMzVzUkZ2UHFvNTJFYzBZbnRmSkVFClhtb1FOTldtRkRjT2M0UkpYeFVn
            c3NnTEhjTjAwSTNsT1Myd0Q1T21RK3MKLS0tIDQvbXRpUUhiNmlPVkhOUVZXQTMr
            MlUvNEFGQzVFMCt0VDdsRnU1V1N6ZVUKHrq0ZnGr5Cl61eDGxwAgUu0YEridVnlA
            daTPsSaddtF++00FVniQ3Qt2zcOqz9J6QdK6zkQxSz1KJoKFrCBRIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T01:18:54Z"
    mac: ENC[AES256_GCM,data:Bgwdt5dT6WnFBJ9IcRv+n/gdy8mWKcSjXvxyiDuxPuvzGA+JpYcrUD42hq/ZZF2ViAcWmjuATGSso/7Cm4hP693x4gdwojdgwXQoacZoQHyLvA2k48Z+PFgqcxTN37mQpRICl4pH6KFOn3RNuz1JGRpcNhlVbNe9YpnhWMECwyQ=,iv:lBvdl07gnpkk56J8kcCvpgKZ2r3o6Wsn8mnCsppKT9Y=,tag:zfNBwGCI5sGccdSRYBjwgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
