apiVersion: v1
kind: Secret
metadata:
    name: samplesecret
    namespace: default
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:PR076D6+STmavRtp,iv:bOh9e6Q3XDAhPD6bGYjhJJ40UtyYQUZnSxIUnSEjn1w=,tag:Pw8e5eq38k1Hk+NnP5IFkQ==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ1RCT3dtemNPSEJWQWpz
            ZWt4OWtOaUoxSGtwejAvZHBmdnBoTlJDTHhnCnkrMGlOdDkyZTJ6TnNzN0NSZkNU
            WE0wbTVwV2tTMGw4YXpwWWZ2Q2gyN1EKLS0tIHJ4eW55MWJ4bkhIWDl3QmhhOTJZ
            ZFJDY1daVHpvZDErTHM3MVcycDVTcmsKaBj+OhKztrvheM0fSsgSwK7JVNI3dbAu
            dXPfANOE4t/xdEPLnwk60EzMA2WGIP+SKsnADYri8Vze+R/qSolYgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T01:12:45Z"
    mac: ENC[AES256_GCM,data:5/9kQ/aZIbZMqr+eVl+TsG/tf9NxN//v9l2cC3DORqHcM23ICwi5niV/WUYiVgaBGeyKVOrApzcmgRLKUwQ5xfesk5CYauG3wnwa60Z7Ia9PCAx83yHFf/Ei99eAv0X7AS2VwgslHqjioz2Tcb0duGA1nT/T8TugLE+a2N/Clhs=,iv:tInF1LcuibsIf5Humdz6hDVhBgWtYohoKhcRfkkDGHE=,tag:bO3d6HayJj2kHq6x+Wdiug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
