keys:
  - &master age1xfwuvqdup6uasvn8xp855nvnr57454ywuqnyv8c4cx7l6e84yuxqgq3srv
  - &hosts
    - &files age1a7t9sszcjumknwy5gerqham4wyymfzadjqwsrgg52p4snmn2aglqyyqzcs
    - &couchdb age17c9yzwcur0jnywnv5nczsanvh0jr08nnlumdkxdq7mqxtunqvsrql45uxh
creation_rules:
  - path_regex: ^terraform/terraform\.secrets\.yaml$
    key_groups:
      - age:
          - *master
  - path_regex: nix/hosts/files/secrets\.(yaml|ini)
    key_groups:
      - age:
          - *files
          - *master
  - path_regex: nix/hosts/couchdb/secrets\.(yaml|ini)
    key_groups:
      - age:
          - *couchdb
          - *master
