apiVersion: v1
data:
    hello: ENC[AES256_GCM,data:RuhY1VNa3zs=,iv:FFEDr6kEqohsd4PcHsUTtKb1Mi3+PVcJVTxJOuePLHE=,tag:ZHdRo7nOjqWISjZLgP8Qgw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sopstest
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDI0a0NWYXVuRFhQd0NM
            emJ3ZHI1OU5oWFBUeWtrSnZnZkExV1VhNWcwClpXNDVhT0p0dWxMRjZMcExibXBj
            M3BFSCt3ckhzd0svck5pZlVtQ0hKOWMKLS0tIEpYcGlYanRaQnZmVVNsdnlKa0Uz
            azFFTmlBMWZFa2dvMXFqZnpPdVNzancKlTafm++VahgJqDWL4Jn6Uyl1SiX9tBfD
            So+zYfj+BkoZKe8og52WfdeuuQISu242c9IDSkzHObS1t6Em0jRkTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T20:22:15Z"
    mac: ENC[AES256_GCM,data:RyrssGvRV+WqSB3YqJDIhNo6uKhCCbEKwp+8qwue76L3LsuLIkx52BiFJ7VEE10C9eQ1D1zGLWKNcD7u8c4XJq9eX/0pTvYBzInXgcK+/TiF1CcUrnS6gdsnCyWLfRGXzoaJGr6w5RoT87i1tvNbPg/G9kiEkEAsXLuRdDwjhr0=,iv:Tim+nNZKgPTFdZ1Pu0FLsoxGbFGUXtJKE4hAM4JdkaI=,tag:9YDUxYdqLm6OVeLLSGAerA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
