---
- name: Configure NAT on Proxmox host
  hosts: pve
  become: true
  tasks:
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Set up NAT for vmbr1
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: vmbr0
        source: "10.10.10.0/24"
        jump: MASQUERADE

